version: '3'

services:
  db:
    image: mariadb
    volumes:
      - ./docker/discoball.sql:/docker-entrypoint-initdb.d/discoball.sql
    environment:
      MYSQL_ROOT_PASSWORD: "root" # Only used for development, change this
      MYSQL_DATABASE: "discoball"
  bot:
    build: .
    command: "./docker/wait-for-it.sh db:3306 -- node --debug=5858 index.js"
    depends_on:
      - db
    ports:
      - 5858:5858
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: "root"
      MYSQL_ROOT_PASSWORD: "root"
